import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '@/components/Cabecalho/cabecalho'
import Rodape  from '@/components/Rodape/rodape'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Challenge04 - Tropinha do Challenge',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>

        <Cabecalho /> 
        <Rodape /> 
        
    </html>
  )
}
